import { Destination, Booking, User, Review } from '../types';
import { PLACEHOLDER_IMAGES } from '../constants/images';

export const mockDestinations: Destination[] = [
  {
    id: '1',
    name: 'Paris, France',
    country: 'France',
    description: 'Experience the magic of the City of Light with its iconic landmarks, world-class museums, and exquisite cuisine. From the Eiffel Tower to the Louvre, Paris offers an unforgettable journey through art, history, and romance.',
    shortDescription: 'The City of Light awaits with romance and culture',
    imageUrl: PLACEHOLDER_IMAGES.destinations.paris,
    images: [
      PLACEHOLDER_IMAGES.destinations.paris,
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800',
    ],
    rating: 4.8,
    reviews: 2543,
    price: 1299,
    duration: '7 days',
    category: 'Cultural',
    featured: true,
    popular: true,
    latitude: 48.8566,
    longitude: 2.3522,
    highlights: [
      'Eiffel Tower visit',
      'Louvre Museum tour',
      'Seine River cruise',
      'Montmartre exploration',
    ],
    amenities: ['Hotel', 'Breakfast', 'Tour Guide', 'Airport Transfer'],
  },
  {
    id: '2',
    name: 'Tokyo, Japan',
    country: 'Japan',
    description: 'Immerse yourself in the perfect blend of traditional and modern in Tokyo. Explore ancient temples, cutting-edge technology, and world-renowned cuisine in one of the most dynamic cities on Earth.',
    shortDescription: 'Where tradition meets innovation',
    imageUrl: PLACEHOLDER_IMAGES.destinations.tokyo,
    images: [
      PLACEHOLDER_IMAGES.destinations.tokyo,
      'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800',
      'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800',
    ],
    rating: 4.9,
    reviews: 3124,
    price: 1899,
    duration: '10 days',
    category: 'Cultural',
    featured: true,
    popular: true,
    latitude: 35.6762,
    longitude: 139.6503,
    highlights: [
      'Mount Fuji day trip',
      'Tsukiji Fish Market',
      'Senso-ji Temple',
      'Shibuya Crossing',
    ],
    amenities: ['Hotel', 'Breakfast', 'Tour Guide', 'JR Pass', 'Airport Transfer'],
  },
  {
    id: '3',
    name: 'Bali, Indonesia',
    country: 'Indonesia',
    description: 'Discover paradise on Earth in Bali. With stunning beaches, lush rice terraces, ancient temples, and warm hospitality, Bali offers the perfect tropical escape.',
    shortDescription: 'Island paradise with stunning beaches',
    imageUrl: PLACEHOLDER_IMAGES.destinations.bali,
    images: [
      PLACEHOLDER_IMAGES.destinations.bali,
      'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
      'https://images.unsplash.com/photo-1570789210967-2cac24afeb00?w=800',
    ],
    rating: 4.7,
    reviews: 1876,
    price: 899,
    duration: '6 days',
    category: 'Beach',
    featured: false,
    popular: true,
    latitude: -8.3405,
    longitude: 115.0920,
    highlights: [
      'Tanah Lot Temple',
      'Ubud Rice Terraces',
      'Beach hopping',
      'Balinese spa experience',
    ],
    amenities: ['Resort', 'All meals', 'Spa access', 'Airport Transfer'],
  },
  {
    id: '4',
    name: 'Maldives',
    country: 'Maldives',
    description: 'Escape to the ultimate luxury destination with crystal-clear waters, white sandy beaches, and overwater bungalows. The Maldives offers unparalleled relaxation and natural beauty.',
    shortDescription: 'Luxury overwater paradise',
    imageUrl: PLACEHOLDER_IMAGES.destinations.maldives,
    images: [
      PLACEHOLDER_IMAGES.destinations.maldives,
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
      'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800',
    ],
    rating: 4.9,
    reviews: 2156,
    price: 2499,
    duration: '5 days',
    category: 'Luxury',
    featured: true,
    popular: true,
    latitude: 3.2028,
    longitude: 73.2207,
    highlights: [
      'Overwater villa stay',
      'Snorkeling & diving',
      'Sunset cruise',
      'Spa treatments',
    ],
    amenities: ['Luxury Resort', 'All inclusive', 'Water sports', 'Seaplane transfer'],
  },
  {
    id: '5',
    name: 'Swiss Alps',
    country: 'Switzerland',
    description: 'Experience breathtaking mountain scenery in the Swiss Alps. Perfect for adventure seekers and nature lovers, with world-class skiing, hiking, and charming alpine villages.',
    shortDescription: 'Majestic mountains and alpine charm',
    imageUrl: PLACEHOLDER_IMAGES.destinations.switzerland,
    images: [
      PLACEHOLDER_IMAGES.destinations.switzerland,
      'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    rating: 4.8,
    reviews: 1543,
    price: 1699,
    duration: '8 days',
    category: 'Nature',
    featured: false,
    popular: true,
    latitude: 46.8182,
    longitude: 8.2275,
    highlights: [
      'Jungfraujoch excursion',
      'Lake Geneva cruise',
      'Swiss chocolate factory',
      'Mountain railway rides',
    ],
    amenities: ['Hotel', 'Breakfast', 'Swiss Travel Pass', 'Airport Transfer'],
  },
  {
    id: '6',
    name: 'New York City',
    country: 'USA',
    description: 'The city that never sleeps offers iconic landmarks, world-class entertainment, and diverse culture. From Times Square to Central Park, NYC is an unforgettable urban adventure.',
    shortDescription: 'The city that never sleeps',
    imageUrl: PLACEHOLDER_IMAGES.destinations.newYork,
    images: [
      PLACEHOLDER_IMAGES.destinations.newYork,
      'https://images.unsplash.com/photo-1522083165195-3424ed129620?w=800',
      'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800',
    ],
    rating: 4.7,
    reviews: 3876,
    price: 1499,
    duration: '6 days',
    category: 'Cultural',
    featured: false,
    popular: true,
    latitude: 40.7128,
    longitude: -74.0060,
    highlights: [
      'Statue of Liberty',
      'Empire State Building',
      'Broadway show',
      'Central Park tour',
    ],
    amenities: ['Hotel', 'Breakfast', 'Metro card', 'Airport Transfer'],
  },
  {
    id: '7',
    name: 'Santorini, Greece',
    country: 'Greece',
    description: 'Experience the stunning beauty of Santorini with its white-washed buildings, blue-domed churches, and spectacular sunsets over the Aegean Sea.',
    shortDescription: 'Iconic white and blue paradise',
    imageUrl: PLACEHOLDER_IMAGES.destinations.santorini,
    images: [
      PLACEHOLDER_IMAGES.destinations.santorini,
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800',
    ],
    rating: 4.9,
    reviews: 2234,
    price: 1399,
    duration: '5 days',
    category: 'Beach',
    featured: true,
    popular: true,
    latitude: 36.3932,
    longitude: 25.4615,
    highlights: [
      'Oia sunset viewing',
      'Wine tasting tour',
      'Volcanic beach visit',
      'Caldera cruise',
    ],
    amenities: ['Boutique Hotel', 'Breakfast', 'Wine tasting', 'Airport Transfer'],
  },
  {
    id: '8',
    name: 'Dubai, UAE',
    country: 'United Arab Emirates',
    description: 'Experience the epitome of luxury and innovation in Dubai. From the world\'s tallest building to gold-covered markets, Dubai offers an extraordinary blend of tradition and futurism.',
    shortDescription: 'Luxury and innovation in the desert',
    imageUrl: PLACEHOLDER_IMAGES.destinations.dubai,
    images: [
      PLACEHOLDER_IMAGES.destinations.dubai,
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
      'https://images.unsplash.com/photo-1582672060674-bc2bd808a8b5?w=800',
    ],
    rating: 4.8,
    reviews: 2987,
    price: 1799,
    duration: '5 days',
    category: 'Luxury',
    featured: false,
    popular: true,
    latitude: 25.2048,
    longitude: 55.2708,
    highlights: [
      'Burj Khalifa visit',
      'Desert safari',
      'Dubai Mall shopping',
      'Palm Jumeirah tour',
    ],
    amenities: ['5-star Hotel', 'Breakfast', 'Desert Safari', 'Airport Transfer'],
  },
  {
    id: '9',
    name: 'Iceland Adventure',
    country: 'Iceland',
    description: 'Explore the land of fire and ice with its dramatic landscapes, glaciers, geysers, and Northern Lights. Iceland offers unparalleled natural wonders.',
    shortDescription: 'Land of fire, ice, and Northern Lights',
    imageUrl: PLACEHOLDER_IMAGES.destinations.iceland,
    images: [
      PLACEHOLDER_IMAGES.destinations.iceland,
      'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=800',
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    ],
    rating: 4.9,
    reviews: 1654,
    price: 2199,
    duration: '7 days',
    category: 'Entertainment',
    featured: true,
    popular: false,
    latitude: 64.9631,
    longitude: -19.0208,
    highlights: [
      'Golden Circle tour',
      'Blue Lagoon spa',
      'Northern Lights hunting',
      'Glacier hiking',
    ],
    amenities: ['Hotel', 'Breakfast', '4x4 rental', 'Airport Transfer'],
  },
  {
    id: '10',
    name: 'Rome, Italy',
    country: 'Italy',
    description: 'Walk through history in the Eternal City. Rome offers ancient ruins, world-class art, delicious cuisine, and the romantic charm of Italian culture.',
    shortDescription: 'The Eternal City of history and art',
    imageUrl: PLACEHOLDER_IMAGES.destinations.rome,
    images: [
      PLACEHOLDER_IMAGES.destinations.rome,
      'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800',
      'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800',
    ],
    rating: 4.7,
    reviews: 3456,
    price: 1199,
    duration: '6 days',
    category: 'Cultural',
    featured: false,
    popular: true,
    latitude: 41.9028,
    longitude: 12.4964,
    highlights: [
      'Colosseum tour',
      'Vatican Museums',
      'Trevi Fountain',
      'Roman Forum',
    ],
    amenities: ['Hotel', 'Breakfast', 'Skip-the-line tickets', 'Airport Transfer'],
  },
];

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  avatar: PLACEHOLDER_IMAGES.user,
  phone: '+1 234 567 8900',
  dateOfBirth: '1990-05-15',
  nationality: 'United States',
  favorites: ['1', '3', '7'],
  bookings: ['1', '2'],
  createdAt: '2023-01-15T00:00:00.000Z',
};

export const mockBookings: Booking[] = [
  {
    id: '1',
    destination: mockDestinations[0],
    userId: '1',
    startDate: '2025-11-01',
    endDate: '2025-11-08',
    guests: 2,
    totalPrice: 1299,
    status: 'confirmed',
    createdAt: '2025-10-15T00:00:00.000Z',
    paymentMethod: 'Credit Card',
    specialRequests: 'Room with view, late check-in',
  },
  {
    id: '2',
    destination: mockDestinations[6],
    userId: '1',
    startDate: '2025-12-15',
    endDate: '2025-12-20',
    guests: 2,
    totalPrice: 1399,
    status: 'pending',
    createdAt: '2025-10-18T00:00:00.000Z',
    paymentMethod: 'PayPal',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    userId: '2',
    userName: 'Sarah Johnson',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    destinationId: '1',
    rating: 5,
    comment: 'Absolutely amazing experience! Paris exceeded all expectations. The tour was well organized and our guide was fantastic.',
    createdAt: '2025-10-10T00:00:00.000Z',
    images: [],
  },
  {
    id: '2',
    userId: '3',
    userName: 'Michael Chen',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    destinationId: '1',
    rating: 4,
    comment: 'Great trip overall. The hotel was comfortable and the attractions were breathtaking. Would recommend!',
    createdAt: '2025-10-08T00:00:00.000Z',
  },
];


