server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Travelling_App_BE
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/travelling_db
      auto-index-creation: false
      
    # redis:
    #   host: localhost
    #   port: 6379
    #   timeout: 2000ms
      
  cache:
    type: simple
    # redis:
    #   time-to-live: 600000

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForTravellingApp2024}
  expiration: 86400000 # 24 hours

# External APIs
external:
  apis:
    unsplash:
      access-key: ${UNSPLASH_ACCESS_KEY:your-unsplash-key}
      base-url: https://api.unsplash.com
    openweather:
      api-key: ${OPENWEATHER_API_KEY:your-openweather-key}
      base-url: https://api.openweathermap.org

# Logging
logging:
  level:
    fit.se.travelling_app_be: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb: DEBUG

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
